version: "2"

services:
  mysql:
    image: postgres:9.3-alpine
    environment:
      - POSTGRES_PASSWORD=alfresco
      - POSTGRES_USER=alfresco
      - POSTGRES_DB=alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - 5432:5432
  alfresco:
    image: juanrojas1997/alfresco:1.0
    ports:
      - 8080:8080
      - 8983:8983
      - 3306:3306