version: "2"

networks:
  internal:
    ipam:
      config:
        - subnet: 172.0.0.0/24

services:
  postgres:
    image: juanrojas1997/postgres:latest
    environment:
      - POSTGRES_PASSWORD=alfresco
      - POSTGRES_USER=alfresco
      - POSTGRES_DB=alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - 5432:5432
    networks:
      internal:
        ipv4_address: 172.0.0.2
  alfresco:
    image: juanrojas1997/alfresco:latest
    ports:
      - 8080:8080
      - 8983:8983
      - 3306:3306
    networks:
      internal:
        ipv4_address: 172.0.0.3